/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  BasePoolUserData,
  BasePoolUserDataInterface,
} from "../../../../../@balancer-labs/v2-interfaces/contracts/pool-utils/BasePoolUserData";

const _abi = [
  {
    inputs: [],
    name: "RECOVERY_MODE_EXIT_KIND",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608b610038600b82828239805160001a607314602b57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806309564cb1146038575b600080fd5b603f60ff81565b60405160ff909116815260200160405180910390f3fea2646970667358221220facacc0a8117d91b72aa479588f804114f4c95f70d230123327b7374ccdca24264736f6c634300080f0033";

type BasePoolUserDataConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BasePoolUserDataConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BasePoolUserData__factory extends ContractFactory {
  constructor(...args: BasePoolUserDataConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<BasePoolUserData> {
    return super.deploy(overrides || {}) as Promise<BasePoolUserData>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): BasePoolUserData {
    return super.attach(address) as BasePoolUserData;
  }
  override connect(signer: Signer): BasePoolUserData__factory {
    return super.connect(signer) as BasePoolUserData__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BasePoolUserDataInterface {
    return new utils.Interface(_abi) as BasePoolUserDataInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BasePoolUserData {
    return new Contract(address, _abi, signerOrProvider) as BasePoolUserData;
  }
}
